services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    command: celery -A praxia_backend worker -l INFO
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - web
      - redis
    restart: always

  celery-beat:
    build: .
    command: celery -A praxia_backend beat -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - web
      - redis
    restart: always

  monai:
    image: projectmonai/monai:latest
    ports:
      - "8888:8888"
    volumes:
      - ./data/models:/models

  sam:
    image: sam-med2d:latest
    build:
      context: .
      dockerfile: Dockerfile.sam
    volumes:
      - ./data/models:/models

volumes:
  postgres_data:
  static_volume:
  media_volume:
