services:
  web:
    build: .
    volumes:
      - ./:/app:delegated
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=development
      - SERVICE_NAME=web
    depends_on:
      - redis
    restart: always
    networks:
      - praxia-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    networks:
      - praxia-network

  celery:
    build: .
    command: celery -A praxia_backend worker -l INFO
    volumes:
      - ./:/app:delegated
      - ./data:/app/data
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - redis
      - web
    restart: always
    networks:
      - praxia-network

  celery-beat:
    build: .
    command: celery -A praxia_backend beat -l INFO
    volumes:
      - ./:/app:delegated
      - ./data:/app/data
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: always
    networks:
      - praxia-network

  monai:
    image: projectmonai/monai:latest
    platform: linux/amd64
    ports:
      - "8888:8888"
    volumes:
      - ./data/models:/app/data/models
    networks:
      - praxia-network
    shm_size: "1g"
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    command: ["python", "-c", "import monai; print('MONAI initialized successfully'); import time; [time.sleep(3600) for _ in iter(int, 1)]"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - praxia-network

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin_password}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    restart: always
    networks:
      - praxia-network

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=es,en,fr
      - LT_THREADS=4
      - LT_MEMORY=100M
      - LT_UPDATE_MODELS=false
    restart: always
    networks:
      - praxia-network

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    restart: always
    networks:
      - praxia-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
    restart: always
    networks:
      - praxia-network
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    command:
      - '--docker_only=true'
      - '--disable_metrics=disk,diskIO,network,tcp,udp,percpu,sched,process'

  redis-exporter:
    image: oliver006/redis_exporter
    env_file:
      - ./.env
    environment:
      - REDIS_ADDR=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
    restart: always
    networks:
      - praxia-network

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    env_file:
      - ./.env
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}?sslmode=disable
    restart: always
    networks:
      - praxia-network

networks:
  praxia-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  prometheus_data:
  grafana_data:
