services:
  web:
    build: .
    volumes:
      - ./:/app:delegated
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - model_volume:/app/data/models:delegated
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=development
      - SERVICE_NAME=web
      - CELERY_WORKER_MAX_MEMORY_PER_CHILD=500000  # 500MB
      - CELERY_WORKER_MAX_TASKS_PER_CHILD=100
    depends_on:
      - redis
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1.5G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
    networks:
      - praxia-network
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: .
    command: celery -A praxia_backend worker -l INFO --concurrency=2 --max-tasks-per-child=50 --max-memory-per-child=400000
    volumes:
      - ./:/app:delegated
      - ./data:/app/data:delegated
      - media_volume:/app/media
      - model_volume:/app/data/models:delegated
    env_file:
      - ./.env
    environment:
      - SERVICE_NAME=celery
      - CELERY_WORKER_MAX_MEMORY_PER_CHILD=400000  # 400MB
      - CELERY_WORKER_MAX_TASKS_PER_CHILD=50
      - CELERY_WORKER_DISABLE_RATE_LIMITS=True
      - OMP_NUM_THREADS=2
      - CUDA_VISIBLE_DEVICES=""  # Disable CUDA for workers
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  celery-beat:
    build: .
    command: celery -A praxia_backend beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./:/app:delegated
      - ./data:/app/data
      - model_volume:/app/data/models
    env_file:
      - ./.env
    environment:
      - SERVICE_NAME=celery-beat
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  celery-monitor:
    build: .
    command: celery -A praxia_backend flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - ./.env
    environment:
      - SERVICE_NAME=celery-monitor
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  monai:
    image: projectmonai/monai:latest
    platform: linux/amd64
    ports:
      - "8888:8888"
    volumes:
      - model_volume:/app/data/models:delegated
    networks:
      - praxia-network
    shm_size: "2g"
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: ["python", "-c", "import monai; print('MONAI initialized successfully'); import time; [time.sleep(3600) for _ in iter(int, 1)]"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin_password}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=es,en,fr
      - LT_THREADS=2
      - LT_MEMORY=256M
      - LT_UPDATE_MODELS=false
      - LT_DISABLE_WEB_UI=true
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
      - '--collector.cpu'
      - '--collector.meminfo'
      - '--collector.diskstats'
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    networks:
      - praxia-network
    command:
      - '--docker_only=true'
      - '--disable_metrics=disk,diskIO,network,tcp,udp,percpu,sched,process'
      - '--housekeeping_interval=30s'
      - '--max_housekeeping_interval=35s'
      - '--event_storage_event_limit=default=0'
      - '--event_storage_age_limit=default=0'
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  redis-exporter:
    image: oliver006/redis_exporter
    env_file:
      - ./.env
    environment:
      - REDIS_ADDR=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    env_file:
      - ./.env
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}?sslmode=disable
    restart: always
    networks:
      - praxia-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  praxia-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  model_volume:
  prometheus_data:
  grafana_data:
