# Generated by Django 5.2.1 on 2025-05-23 10:49

import api.models.ai
import api.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.models.user.user_profile_image_path
            ),
        ),
        migrations.AlterField(
            model_name="xrayanalysis",
            name="image",
            field=models.ImageField(upload_to=api.models.ai.user_xray_path),
        ),
    ]
